name: Move Use Tag

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  movetag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Move the use tag
      run: |
        TAG="use"
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git tag -fa "${TAG}" -m 'Moved by action'
        git push origin "${TAG}" --force
